
["Adventurer Zombie Equipment"]
	#Items / chance of spawning with it
	"Head Slot" = ["minecraft:chainmail_helmet|25", "minecraft:iron_helmet|10", "minecraft:golden_helmet|10"]
	"Chest Slot" = ["minecraft:chainmail_chestplate|25", "minecraft:iron_chestplate|20", "minecraft:golden_chestplate|20"]
	"Main Hand Slot" = ["minecraft:stone_sword|25", "minecraft:golden_sword|20", "minecraft:iron_axe|5", "minecraft:golden_axe|5", "minecraft:iron_sword|1"]

